import { authenticateFindogAgentAdmin } from "@/lib/findog-agent/auth";
import {
  findogAgentEnqueueBlockReason,
  findogAgentErrorResponse,
  findogAgentJson,
  parseFindogAgentEnqueueBody,
  requireFindogAgentStore,
  toFindogAgentRunDto,
} from "@/lib/findog-agent/api";
import { UserVisibleError } from "@/lib/errors";

export const runtime = "nodejs";

/**
 * Idempotent enqueue of a research question.
 *
 * The conversation id is generated by the client, so the first POST atomically
 * creates the conversation, the user question and the queued run through the
 * existing enqueue function. Replaying the same idempotency key returns the
 * existing run and never creates a second question or a duplicate model call.
 */
export async function POST(request: Request) {
  try {
    const { store, client } = requireFindogAgentStore();
    const user = await authenticateFindogAgentAdmin(request, client);

    let body: unknown;
    try {
      body = await request.json();
    } catch {
      throw new UserVisibleError("Die Anfrage enthält kein gültiges JSON.", 400);
    }
    const input = parseFindogAgentEnqueueBody(body);

    const snapshot = await store.getSettings();
    const block = findogAgentEnqueueBlockReason(snapshot);
    if (block) {
      return findogAgentJson({ error: block.message, code: block.code }, block.status);
    }

    const run = await store.enqueueRun({
      ownerId: user.id,
      conversationId: input.conversationId,
      idempotencyKey: input.idempotencyKey,
      settingsRevision: snapshot.revision as number,
      question: input.question,
      conversationTitle: input.conversationTitle,
    });

    return findogAgentJson({ run: toFindogAgentRunDto(run) }, 202);
  } catch (error) {
    return findogAgentErrorResponse(error);
  }
}
